"""create problems table and fix catalog autoincrement

Revision ID: 0139c27d4d45
Revises: 7cd990a933d8
Create Date: 2026-09-29 02:41:25.282074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0139c27d4d45'
down_revision: Union[str, None] = '7cd990a933d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('frontend_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title_slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('description_html', sa.Text(), nullable=False),
    sa.Column('example_testcases', sa.Text(), nullable=False),
    sa.Column('topic_tags', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('frontend_id')
    )
    op.create_index(op.f('ix_problems_title_slug'), 'problems', ['title_slug'], unique=True)
    # ### end Alembic commands ###

    # manual fix: autogenerate can't detect SERIAL/identity changes on an existing column
    op.execute("ALTER TABLE problem_catalog ALTER COLUMN frontend_id DROP DEFAULT")
    op.execute("DROP SEQUENCE IF EXISTS problem_catalog_frontend_id_seq")


def downgrade() -> None:
    op.execute(
        "CREATE SEQUENCE IF NOT EXISTS problem_catalog_frontend_id_seq OWNED BY problem_catalog.frontend_id"
    )
    op.execute(
        "ALTER TABLE problem_catalog ALTER COLUMN frontend_id "
        "SET DEFAULT nextval('problem_catalog_frontend_id_seq')"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problems_title_slug'), table_name='problems')
    op.drop_table('problems')
    # ### end Alembic commands ###
