"""add current problem to room

Revision ID: 05f0e88c777b
Revises: 0139c27d4d45
Create Date: 2026-09-30 00:13:52.454223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f0e88c777b'
down_revision: Union[str, None] = '0139c27d4d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('current_problem_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rooms', 'problems', ['current_problem_id'], ['frontend_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'current_problem_id')
    # ### end Alembic commands ###
