"""create problem catalog table

Revision ID: 7cd990a933d8
Revises: 54dc343e12a0
Create Date: 2026-09-29 02:33:26.081555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd990a933d8'
down_revision: Union[str, None] = '54dc343e12a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_catalog',
    sa.Column('frontend_id', sa.Integer(), nullable=False),
    sa.Column('title_slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('frontend_id')
    )
    op.create_index(op.f('ix_problem_catalog_title'), 'problem_catalog', ['title'], unique=False)
    op.create_index(op.f('ix_problem_catalog_title_slug'), 'problem_catalog', ['title_slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_catalog_title_slug'), table_name='problem_catalog')
    op.drop_index(op.f('ix_problem_catalog_title'), table_name='problem_catalog')
    op.drop_table('problem_catalog')
    # ### end Alembic commands ###
