"""add code snippets to problems

Revision ID: 8cacd5bf6562
Revises: 05f0e88c777b
Create Date: 2026-10-09 14:39:02.383057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cacd5bf6562'
down_revision: Union[str, None] = '05f0e88c777b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('code_snippets', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'code_snippets')
    # ### end Alembic commands ###
